package io.github.supermonster003.autojs6.plugin.ace.editor.core.diagnostics

data class AceDiagnosticsSnapshot(
    val engineType: String,
    val aceHealthState: String?,
    val lastFailureType: String?,
    val lastFailureMessage: String?,
    val lastFailureFatal: Boolean?,
    val assetUrl: String?,
    val webViewVersion: String,
    val androidVersion: String,
    val lspEnabled: Boolean,
    val lspState: String,
    val lspTransport: String? = null,
    val lspServerUri: String? = null,
    val lspRootUri: String? = null,
    val lspDocumentUri: String? = null,
    val lspFallback: String? = null,
    val lspCompletionProvider: String? = null,
    val lspHoverProvider: String? = null,
    val lspDiagnosticProvider: String? = null,
    val lspSignatureProvider: String? = null,
    val lspServerAvailable: Boolean = false,
    val lspStartSupported: Boolean = false,
    val lspSessionRevision: Long = 0L,
    val lspRuntimeState: String? = null,
    val aceFont: String?,
    val fileSizeBytes: Long?,
    val largeFilePolicy: String,
    val textMirrorRevision: Long?,
    val jsRevision: String?,
    val lastReadyAtUptimeMillis: Long?,
    val lastFirstPaintAtUptimeMillis: Long?,
    val lastStateAtUptimeMillis: Long?,
    val lastHeartbeatAtUptimeMillis: Long?,
    val lastHeartbeatSuspendedAtUptimeMillis: Long?,
    val lastHeartbeatResumedAtUptimeMillis: Long?,
    val heartbeatSuspendedReason: String?,
    val lastImeState: String?,
    val lastImeHeight: Int?,
    val lastImeRequestAtUptimeMillis: Long?,
    val lastShowSoftInputAtUptimeMillis: Long?,
    val lastHideSoftInputAtUptimeMillis: Long?,
    val lastImeTransitionStartedAtUptimeMillis: Long?,
    val lastImeTransitionEndedAtUptimeMillis: Long?,
    val lastImeIgnoredRequestReason: String?,
    val lastResizeAtUptimeMillis: Long?,
    val pendingAceResizeReason: String?,
    val lastAceResizeScheduledReason: String?,
    val lastAceResizeScheduledAtUptimeMillis: Long?,
    val lastAceResizeDispatchedReason: String?,
    val lastAceResizeDispatchedAtUptimeMillis: Long?,
    val lastAceResizeCompletedReason: String?,
    val lastAceResizeCompletedAtUptimeMillis: Long?,
    val lastActionModeAtUptimeMillis: Long?,
    val viewportPolicy: String?,
    val lastViewportPolicyEvent: String?,
    val lastViewportPolicyEventAtUptimeMillis: Long?,
    val lastViewportPolicyImeVisible: Boolean?,
    val lastViewportPolicyBottomInset: Int?,
    val lastHostImeVisible: Boolean?,
    val lastHostImeBottomInset: Int?,
    val lastHostImeEventAtUptimeMillis: Long?,
    val lastBridgeEventName: String?,
    val currentBridgeEventWindowCount: Int,
    val lastBridgeEventWindowCount: Int,
    val maxBridgeEventWindowCount: Int,
    val maxBridgeEventWindowStartedAtUptimeMillis: Long?,
    val runtimeEventHistory: List<String>,
    val createdAtEpochMillis: Long = System.currentTimeMillis(),
)
